# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Braids < Formula
  desc "Config-driven API composition — Terraform for APIs"
  homepage "https://braids.dev"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/braidsdev/braids/releases/download/v0.3.0/braids_darwin_amd64.tar.gz"
      sha256 "46ff4902f4766c9a9155809c151dd6d564e0e0ddc8244abe96ddfa1327ae986b"

      define_method(:install) do
        bin.install "braids"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/braidsdev/braids/releases/download/v0.3.0/braids_darwin_arm64.tar.gz"
      sha256 "77628570e446020721eeb6dc063c5c7394d6d9bbb1169ab2d99ebe817fe017b1"

      define_method(:install) do
        bin.install "braids"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/braidsdev/braids/releases/download/v0.3.0/braids_linux_amd64.tar.gz"
      sha256 "681fe09298bf25283d83c72331b15e5a1b978e305ef8dbe6f66c7ea1a68059a7"
      define_method(:install) do
        bin.install "braids"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/braidsdev/braids/releases/download/v0.3.0/braids_linux_arm64.tar.gz"
      sha256 "f214ba11fd343ce04df599757da4294158fa3e7867a43b9d4acca217a77a1236"
      define_method(:install) do
        bin.install "braids"
      end
    end
  end

  test do
    system "#{bin}/braids", "--version"
  end
end
