# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Braids < Formula
  desc "Config-driven API composition — Terraform for APIs"
  homepage "https://braids.dev"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/braidsdev/braids/releases/download/v0.5.0/braids_darwin_amd64.tar.gz"
      sha256 "ebf560d87245fdf1484f3ca1b47832da5d43cd158f20926f333ab271961c1a5b"

      define_method(:install) do
        bin.install "braids"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/braidsdev/braids/releases/download/v0.5.0/braids_darwin_arm64.tar.gz"
      sha256 "8b244cabb6a6c573f2956c7fc3bc97ee938abdf0a8870ce29c601f1db74b3c51"

      define_method(:install) do
        bin.install "braids"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/braidsdev/braids/releases/download/v0.5.0/braids_linux_amd64.tar.gz"
      sha256 "abce651be5acccaaf1c5290507b2eaa31c8558df7deb558d446118335d421ab5"
      define_method(:install) do
        bin.install "braids"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/braidsdev/braids/releases/download/v0.5.0/braids_linux_arm64.tar.gz"
      sha256 "6cdb5bc40ce46003c45342fa184d12645fe7c3153207c4239a62385d46448ee7"
      define_method(:install) do
        bin.install "braids"
      end
    end
  end

  test do
    system "#{bin}/braids", "--version"
  end
end
