# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Braids < Formula
  desc "Config-driven API composition — Terraform for APIs"
  homepage "https://braids.dev"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/braidsdev/braids/releases/download/v0.4.0/braids_darwin_amd64.tar.gz"
      sha256 "c34df39ebcdbea34c2c783e3761ba128592e663cff448cd6bfb5eefb22268337"

      define_method(:install) do
        bin.install "braids"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/braidsdev/braids/releases/download/v0.4.0/braids_darwin_arm64.tar.gz"
      sha256 "bbe3a1ea1224a524b609130bf9e81b0b56ea305678cb97bf719161aed50bb9bc"

      define_method(:install) do
        bin.install "braids"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/braidsdev/braids/releases/download/v0.4.0/braids_linux_amd64.tar.gz"
      sha256 "4d2557c3ca163782a63f72bd1154279471f66d45a9e6ccacc9aa7e7ca63e0f4d"
      define_method(:install) do
        bin.install "braids"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/braidsdev/braids/releases/download/v0.4.0/braids_linux_arm64.tar.gz"
      sha256 "e044ff0b2c13541b4becbdda6a4ade1af24b5557bc8201507faef95c9dfff50c"
      define_method(:install) do
        bin.install "braids"
      end
    end
  end

  test do
    system "#{bin}/braids", "--version"
  end
end
